### PR TITLE
feat: Add caution note about executing AI generated code.

### LINKED ISSUE #19: Add Note to Caution Users About Executing AI-Generated Code
**Is your feature request related to a problem? Please describe.**
Users may unknowingly execute potentially harmful or suboptimal code generated by AI, leading to security risks or system issues.

**Describe the solution you'd like**
Add a prominently displayed note in the interface to caution users to review and verify the AI-generated `devcontainer.json` file before executing it.

**Describe alternatives you've considered**
- Adding detailed documentation on security best practices, but this note provides immediate and specific guidance.
- Relying solely on user knowledge, which might not be sufficient for all users.

**Additional context**
Include the note near the generated `devcontainer.json` output, ensuring it is visible and clear to the user. This will help mitigate risks associated with executing AI-generated code. Ensure the note emphasizes the importance of reviewing the file thoroughly before running it in their environment.

### PR DESCRIPTION
**Pull request by mobley-trent**
Closes #19 
/claim #19

### CODE REVIEW

**Comment by nkkko** [comment]
@mobley-trent appreciate it, could you please style it accordingly as it can't be on the same level of importance as other sections, this is a caution note.

**Comment by mobley-trent** [comment]
@nkkko updated the background colour and the header text

**Comment by nkkko** [comment]
@mobley-trent I will add a 10$ tip but please style it more subtly and show it only after the devcontainer.json is generated. Currently this is a sore eye. And could deter people from using it.
image

**Comment by mobley-trent** [comment]
@nkkko I added rounded edges to the div as well as a caution emoji to make it less jarring

**Comment by nkkko** [comment]
Sorry, can't accept this, looks terrible:
image

**Comment by mobley-trent** [comment]
It rendered a lot differently on my machine. I'm happy to open another PR

**Pull request closed without merging**
