### PR TITLE
update-readme-and-supabase-migration

### PR DESCRIPTION
**Pull request by madman024**
hey @nkkko , i have made the following changes:

Replaced SQLite setup with Supabase instructions.
Added steps to create the devcontainers table.
Reorganized README: moved configuration before usage.
Updated environment variable setup for Supabase.

/claim https://github.com/daytonaio/devcontainer-generator/issues/36
/closes https://github.com/daytonaio/devcontainer-generator/issues/36
This PR addresses the issue by adding the necessary steps to resolve the problem. We've provided instructions for setting up the devcontainers table with Supabase.Creating table from python code isnt possible with supabase , as much as i have searched so this is the feasible way, @nkkko look into it whenever possible
Please let me know if any changes are needed or if you have any feedback

### CODE REVIEW

**Comment by madman024** [comment]
/claim #36
/closes #36
This PR addresses the issue by adding the necessary steps to resolve the problem. We've provided instructions for setting up the devcontainers table with Supabase.Creating table from python code isnt possible with supabase , as much as i have searched so this is the feasible way, @nkkko look into it whenever possible

**Comment by nkkko** [comment]
hey @madman024 you need to sign your commits (DCO), check errors

**Comment by madman024** [comment]
@nkkko done , plz check it now.

**Comment by mojafa** [comment]
@madman024 I’ve updated main with some changes that affect this PR. Could you please rebase your branch onto the latest main and resolve any conflicts that come up? Once that’s done, we can review the updated changes and move forward.

**Comment by madman024** [comment]
@mojafa i have rebased my branch ,there were no conflicts can u check now

**Comment by mojafa** [comment]
@madman024 thank you. on it now

**Comment by mojafa** [comment]
@madman024 please add screenshots in your readme of how those steps look like.

**Review by nkkko — APPROVED** [review]

**Comment by madman024** [comment]
@nkkko @mojafa thank you for merging the pr, but unfortunately, Stripe accounts are invite-only in India and complicated to set up. Could you please send the payment through another method, such as PayPalor direct bank transfer?i would be really thankfull for that.

**Comment by nkkko** [comment]
pls join our slack and send me DM there @madman024

**Pull request merged**
