### PR TITLE
use tailwind css instead of picocss

### LINKED ISSUE #5: Migrate from Picocss to Tailwind and Cleanup Frontend Code
**Is your feature request related to a problem? Please describe.**
The current project utilizes Picocss for styling the frontend. Tailwind CSS provides a more modern, utility-first approach to styling, which can make the codebase cleaner and more maintainable. Additionally, there is some mix of tailwind already in the frontend that needs to be cleaned up.

**Describe the solution you'd like**
- Replace Picocss with Tailwind CSS for all styling.
- Refactor HTML templates to use Tailwind's utility classes.
- Remove any unused or duplicated CSS and HTML code.

**Additional context**
Please ensure that all sections in `content.py` are updated to reflect the changes. Below are some specific sections that will need modification:
- `hero_section`
- `generator_section`
- `benefits_section`
- `setup_section`
- `examples_section`
- `faq_section`
- `cta_section`
- `footer_section`

Review and update `main.py` and other related files to ensure integration is seamless and effective. Make sure to test thoroughly to maintain the functionality and design consistency.

### PR DESCRIPTION
**Pull request by AliYar-Khan**
Issue Reference(s):
Fixes #5 
/claim #5

Migration to Tailwind CSS

had to install tailwind package as dev dependency and on start of server generate the CSS from main.css to tailwind.css
Also the main.css is also convert to tailwind classes and use the utility provided by tailwind to apply them. Reason for doing this was because in main.js file we have used the class name to add event listeners on the elements like button and it could have break the functionality.

### CODE REVIEW

**Comment by AliYar-Khan** [comment]
@nkkko please take a look here to my work and let me know if there any changes required

**Comment by AliYar-Khan** [comment]
@nkkko Please review the changes and let me know if anything is unclear. Will really appreciate your feedback.

**Comment by nkkko** [comment]
Sorry for the late reply, have been busy. The interface is messed up, especially buttons, see img:
image

It still loads Pico?
image

**Comment by AliYar-Khan** [comment]
I will look into these not sure why it is happening !!!

**Comment by mojafa** [comment]
@AliYar-Khan I’ve updated main with some changes that affect this PR. Could you please rebase your branch onto the latest main and resolve any conflicts that come up? Once that’s done, we can review the updated changes and move forward.

**Comment by AliYar-Khan** [comment]
@mojafa I did updated it

**Comment by mojafa** [comment]
@AliYar-Khan looks like we still have `pico`
Screenshot 2024-12-17 at 23 26 43

**Comment by mojafa** [comment]
Screenshot 2024-12-17 at 23 27 30

**Comment by mojafa** [comment]
Screenshot 2024-12-17 at 23 32 58

**Comment by AliYar-Khan** [comment]
@mojafa yes I am not sure why it is there

**Comment by AliYar-Khan** [comment]
I think Tailwind is not a good choice with Fasthtml. I tried but it is breaking and I am not moving forward with it

**Pull request closed without merging**
